# Generated by Django 5.0.6 on 2024-07-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_item_address_item_age_item_barangay_item_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ZipCode',
            field=models.TextField(),
        ),
    ]
