# Generated by Django 5.0.6 on 2024-07-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_rename_facebook_item_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='College',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Elementary',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Fathers_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Mothers_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Secondary',
        ),
    ]
